### ISSUE TITLE
Login fails since firmware AR01.02.068.10_082720_711.SIP.10

### ISSUE THREAD

**Issue by debfx** [diveflo/arris-tg3442-reboot#2]
Since firmware version AR01.02.068.10_082720_711.SIP.10 login fails with HTTP 403 Forbidden.

Changing the ajaxSet_Password.php request from PUT to POST fixes the issue.
https://github.com/diveflo/arris-tg3442-reboot/blob/7b1e76f2af922ccb7c447b54040e60d314c385bf/arris-tg3442-reboot.py#L52

**Comment by f-s** [comment]
Thanks a million! IPV6 host exposure is now available ...

**Comment by Mershl** [comment]
> Since firmware version AR01.02.068.10_082720_711.SIP.10 login fails with HTTP 403 Forbidden.
> 
> Changing the ajaxSet_Password.php request from PUT to POST fixes the issue.
> 
> https://github.com/diveflo/arris-tg3442-reboot/blob/7b1e76f2af922ccb7c447b54040e60d314c385bf/arris-tg3442-reboot.py#L52

The restart request also needs to be changed from PUT to POST. Else it will silently fail with a 403.
https://github.com/diveflo/arris-tg3442-reboot/blob/master/arris-tg3442-reboot.py#L93

**Comment by diveflo** [comment]
Hi,

I'm working on adding support for this firmware (and the similarly working firmware 01.02.068.11.EURO.PC20) - thanks for figuring out the fix!

Could you tell me what the "short name" for the firmware is? Unfortunately I only have 01.02.068.11.EURO.PC20 currently.

You should be able to see it on the login page written at the bottom and as the property `_ga.swVersion` if you check the page source.
![2020-10-31 02_19_38-Welcome - Chromium](https://user-images.githubusercontent.com/11045082/97767973-fd261680-1b1f-11eb-86e9-a45cc1c9586e.png)
![2020-10-31 02_20_08-view-source_192 168 100 1 - Chromium](https://user-images.githubusercontent.com/11045082/97768010-46766600-1b20-11eb-8cfd-3ddc48200a65.png)

**Comment by Mershl** [comment]
_ga.swVersion = '01.02.068.10.EURO.SIP';

**Comment by Mershl** [comment]
I've forked the latest version and implemented the two adaptions from here + some quality of life changes. https://github.com/Mershl/arris-tg3442-reboot

It's working perfectly with 01.02.068.10.EURO.SIP

**Comment by diveflo** [comment]
I'd like to still support the old versions as I've actually had Vodafone roll-back my firmware more than once ¯\_(ツ)_/¯
Your quality changes sound good though - if you have the time feel free to open up a pull request 👍
I'll push the support for the new firmware in a minute, would be great if you could give it a try:)

**Comment by diveflo** [comment]
@Mershl Thanks for the pull request:)
You've tested it with your firmware, right? So we should be able to close this.
@debfx if it doesn't work for you for some reason please reopen this!

**Comment by Mershl** [comment]
@diveflo Yes. Working perfectly on `01.02.068.10.EURO.SIP`.
